jwt:
  secret: ${JWT_SECRET}
  expiration: 1800000

spring:
  application:
    name: signin

  datasource:
    url: ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PW}

  jpa:
    show-sql: false
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_ID}
            client-secret: ${KAKAO_SECRET}
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-name: Kakao
            client-authentication-method: client_secret_post

          naver:
            client-id: ${NAVER_ID}
            client-secret: ${NAVER_SECRET}
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: ${NAVER_REDIRECT_URI}

          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
            client-name: Google
            redirect-uri: ${GOOGLE_REDIRECT_URI}

          facebook:
            client-id: ${FACEBOOK_ID}
            client-secret: ${FACEBOOK_SECRET}
            scope:
              - email
              - public_profile
            authorization-grant-type: authorization_code
            client-name: Google
            redirect-uri: ${FACEBOOK_REDIRECT_URI}

          github:
            client-id: ${GITHUB_ID}
            client-secret: ${GITHUB_SECRET}
            scope:
              - read:user
              - user:email
            authorization-grant-type: authorization_code
            client-name: Github
            redirect-uri: ${GITHUB_REDIRECT_URI}

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          facebook:
            authorization-uri: https://www.facebook.com/v10.0/dialog/oauth
            token-uri: https://graph.facebook.com/v10.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-name-attribute: id

          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
